### PR TITLE
Edited Navbar 

### PR DESCRIPTION
**Pull request by star-warrior**
Added most of the element in the navbar from the old website, made responsive, changed links for the socials

### CODE REVIEW

**Comment by Nishthajosh** [comment]
1.change the images & text in the hero section.
2. update the stripe
3. instead of eng. write full name by reducing font size

**Review by CodeJet3317 — CHANGES_REQUESTED** [review]
Screenshot 2024-05-21 173258
Change the name in Nav bar from Environs to LD College of Engineering if you want you can decrease the font size according to your convinence

**Comment by star-warrior** [comment]
The SS you posted is changed and committed already, you can checkout in the file changes.
Screenshot 2024-05-21 192244

**Review by CodeJet3317 — APPROVED** [review]

**Comment by star-warrior** [comment]
Stripe and Navbar Fully Ready

**Pull request merged**
